name: Build Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Listar Arquivos do Repositorio
      run: |
        echo "=== LISTA DE ARQUIVOS NO REPOSITÓRIO ==="
        ls -la
        echo "========================================="

    - name: Extrair e Compilar
      run: |
        ARQUIVO_ZIP=$(find . -name "*.zip" | head -n 1)
        if [ -n "$ARQUIVO_ZIP" ]; then
          echo "Extraindo o arquivo encontrado: $ARQUIVO_ZIP"
          unzip "$ARQUIVO_ZIP"
        else
          echo "Nenhum arquivo .zip foi encontrado no repositório!"
        fi
        
        PASTA_REAL=$(find . -name "build.gradle" -exec dirname {} \; | head -n 1)
        if [ -n "$PASTA_REAL" ]; then
          cd "$PASTA_REAL"
          gradle build
        else
          echo "ERRO: O arquivo build.gradle nao existe mesmo após tentar extrair!"
          exit 1
        fi

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: mod-jar
        path: "**/build/libs/*.jar"
